version: '3.6'

services:

  consul:
    container_name: consul
    image: consul:1.4.4
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_UI_BETA: "true"
      CONSUL_LOCAL_CONFIG: '{"connect": {"enabled": true}}'
    ports:
      - 8500:8500
      - 8600:8600

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
      - CONSUL_SERVICE=users
    depends_on:
      - consul
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - REACT_APP_API_GATEWAY_URL=https://nxxxox5cyg.execute-api.eu-west-1.amazonaws.com/v1/execute
      - REACT_APP_EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
      - REACT_APP_SCORES_SERVICE_URL=${REACT_APP_SCORES_SERVICE_URL}
    depends_on:
      - users

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    volumes:
        - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - 3008:8080
    environment:
      - URL=swagger.json
    depends_on:
      - users

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  exercises:
    build:
      context: ./services/exercises
      dockerfile: Dockerfile
    volumes:
      - './services/exercises:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - USERS_SERVICE_URL=http://localhost:5001 # consul connect sidecar proxy
      - SECRET_KEY=my_precious
      - DATABASE_URL=postgres://postgres:postgres@exercises-db:5432/exercises_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@exercises-db:5432/exercises_test
      - CONSUL_SERVICE=exercises
    depends_on:
      - users
      - exercises-db

  exercises-db:
    build:
      context: ./services/exercises/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  scores:
    build:
      context: ./services/scores
      dockerfile: Dockerfile
    volumes:
      - './services/scores:/usr/src/app'
    ports:
      - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - SECRET_KEY=my_precious
      - DATABASE_URL=postgres://postgres:postgres@scores-db:5432/scores_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@scores-db:5432/scores_test
      - USERS_SERVICE_URL=http://users:5000
      - EXERCISES_SERVICE_URL=http://exercises:5000
    depends_on:
      - users
      - scores-db
      - exercises

  scores-db:
    build:
      context: ./services/scores/project/db
      dockerfile: Dockerfile
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
